# Check out https://www.gitpod.io/docs/references/gitpod-yml for syntax.
image:
  file: .devcontainer/Dockerfile

tasks:
  - name: Application
    init: cargo build # Only executes once as part of prebuild. `before` will execute on every start.
    command: cargo dev # Executed on every start and does not need to terminate.

ports:
  - name: API
    description: Exposes the API that can be interacted with.
    port: 3000
    onOpen: notify
    visibility: private

vscode:
  extensions:
    - "vadimcn.vscode-lldb"
    - "anwar.resourcemonitor"
    - "matklad.rust-analyzer"
    - "tamasfe.even-better-toml"
    - "serayuzgur.crates"
