[package]
name = "facade"
version = "0.1.0"
authors = ["Christian Kjaer Laustsen <ckl@codetalk.io>"]
edition = "2018"


[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
warp = "0.3"
warp-reverse-proxy = "0.3"
